apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "repman.fullname" . }}-api
  labels:
    app: {{ template "repman.name" . }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "repman.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "repman.name" . }}-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/repman-configmap.yaml") . | sha256sum }}
        checksum/nginx: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        checksum/php: {{ include (print $.Template.BasePath "/php-ini-configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "repman.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "repman.name" . }}-api
    spec:
      containers:
        - name: fpm
          image: "{{ .Values.images.buddy.repository }}:{{ default .Chart.AppVersion .Values.images.buddy.tag }}"
          imagePullPolicy: {{ .Values.images.buddy.pullPolicy }}
          command: ["/bin/bash", "-c", "--"]
          args:
            - "cp -r /app/public/* /app/public-shared/ && /app/bin/console assets:install && php-fpm"
          envFrom:
            - configMapRef:
                name: {{ template "repman.fullname" . }}
          env:
            {{ include "repman.environmentSecrets" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          resources:
            {{- .Values.api.resources | toYaml | nindent 12 }}
          volumeMounts:
            - mountPath: /app/public-shared
              name: repman-public
            - name: instance-id
              subPath: instance-id
              mountPath: /app/var/instance-id
            - mountPath: {{ .Values.filestorage.path }}
              name: repman-data
            - name: {{  template "repman.fullname" . }}-php-ini
              mountPath: /usr/local/etc/php/conf.d/chart.ini
              subPath: chart.ini
              readOnly: true
        - name: nginx
          image: "{{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}"
          imagePullPolicy: {{ .Values.images.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.servicePort }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - mountPath: /app/public
              name: repman-public
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: nginx-config
          configMap:
            name: {{ template "repman.fullname" . }}-nginx
            items:
              - key: default.conf
                path: default.conf
        - name: instance-id
          configMap:
            name: {{ template "repman.fullname" . }}-instance-id
            items:
              - key: instance-id
                path: instance-id
        - name: repman-public
          emptyDir: {}
        - name: repman-data
        {{- if .Values.filestorage.persistence.enabled }}
        {{- if .Values.filestorage.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.filestorage.persistence.existingClaim }}
        {{- else }}
          persistentVolumeClaim:
            claimName: {{ template "repman.fullname" . }}-data
        {{- end }}
        {{- else }}
          emptyDir: { }
        {{ end }}
        - name: {{ template "repman.fullname" . }}-php-ini
          configMap:
            name: {{ template "repman.fullname" . }}-php-ini
            items:
              - key: ini
                path: chart.ini
