apiVersion: v1
kind: Service
metadata:
  name: {{ template "repman.fullname" . }}-api
  labels:
    app: {{ template "repman.name" . }}-api
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: {{ template "repman.name" . }}-api
