apiVersion: v1
kind: Service
metadata:
  name: {{ include "repman.fullname" . }}-api
  labels:
    {{- include "repman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.serviceType }}
  ports:
    - port: {{ .Values.nginx.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "repman.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "repman.name" . }}-api
