apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "repman.fullname" . }}-nginx
data:
  default:
    server {
      listen {{ .Values.nginx.servicePort }} default_server;
      listen [::]:{{ .Values.nginx.servicePort }} default_server;

      root /app/public/;
      server_name repman;

      error_log /dev/stderr;
      access_log  /dev/stdout;

      index index.php;
    
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection "1; mode=block";

      location ~ \.php$ {
          fastcgi_pass 127.0.0.1:9000;

          set_real_ip_from {{ .Values.nginx.config.setRealIpFrom }};
          real_ip_header {{ .Values.nginx.config.realIpHeader | quote }};

          fastcgi_buffer_size 32k;
          fastcgi_buffers 32 4k;

          include fastcgi_params;

          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
      }

      location / {
          set_real_ip_from {{ .Values.nginx.config.setRealIpFrom }};
          real_ip_header {{ .Values.nginx.config.realIpHeader | quote }};

          try_files $uri /index.php$is_args$args;
      }
    }

